env:
  browser: true
  es2021: true
ignorePatterns:
  - scratches/
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - unused-imports
  - simple-import-sort
  - only-warn
rules:
  simple-import-sort/imports:
    - warn
  simple-import-sort/exports:
    - warn
  unused-imports/no-unused-imports:
    - warn
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: ^_
      args: after-used
      argsIgnorePattern: ^_
  no-unused-vars:
    - off
  no-async-promise-executor:
    - off
