env:
  browser: true
  es2021: true
  node: true
extends: eslint:recommended
plugins:
  - unused-imports
  - simple-import-sort
  - only-warn
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  simple-import-sort/imports:
    - error
  simple-import-sort/exports:
    - error
  unused-imports/no-unused-imports:
    - error
  unused-imports/no-unused-vars:
    - warn
    - vars: all
      varsIgnorePattern: ^_
      args: after-used
      argsIgnorePattern: ^_
  no-unused-vars:
    - off
  no-useless-escape:
    - warn
  no-case-declarations:
    - warn
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always