export enum ErrorMessage {
  InvalidContent = 'Conteúdo inválido!',
  UnknownMessage = 'Mensagem desconhecida!',
  NotMessageAuthor = 'Você não pode deletar essa mensagem pois ela não pertence a você.',
  CannotFetch = 'Não foi possível buscar a mensagem.',
  CouldNotDeleteUnknownMessage = 'Uma mensagem que era para ser deletada não foi encontrada. Ignorando.',
  NotEnoughOptionsSelected = 'Você não selecionou todos os campos necessários. Reinicie seu Discord para resselecionar os valores ou simplesmente escolha outros caso já hajam opções selecionadas.',
  NotAdmin = 'Você não tem permissão para usar esse comando!',
  CannotFetchSheet = 'Não foi possível encontrar a mensagem de submissão do personagem. Por favor, contate o programador.',
  CannotFetchUser = 'Não foi possível encontrar o usuário do personagem. Por favor, contate o programador.',
  CannotCreateChannel = 'Não foi possível criar o canal de discussão. Isso pode ter acontecido porque existem canais demais na categoria. Por favor, contate o programador ou um administrador.',
  BrokenOption = 'Opção inválida encontrada na hora de gerar os seletores somáticos.',
  SheetAlreadyExists = 'Já existe um criador de fichas nesse canal. Para criar outro, primeiro exclua o anterior, administrador.',
  InvalidChannel = 'Um canal inválido foi fornecido para o criador de seletores somáticos.',
  DatabaseError = 'Um erro ocorreu ao tentar salvar o criador de seletores somáticos no banco de dados. Contate um administrador',
  NotAllowedParent = 'Você não pode usar esse comando aqui!',
  UndefinedSelectValue = 'Houve um erro ao processar suas escolhas da seleção pré-formulário. Por favor, tente novamente.',
  CharDatabaseError = 'Houve um erro na hora de processar o salvamento do seu personagem ao banco de dados. Contate um administrador.',
  NoUser = 'Usuário não encontrado no banco de dados. Você talvez nem tenha um personagem.',
  NoLastMessage = 'Você não possui nenhum post no canal atual, ou ele foi deletado.',
  NoLastEmbed = 'O último post não possui um embed, ou ele foi deletado.'
}
