export * as rps from './fun/rps';
export * as embed from './moderation/embed.js';
export * as log from './moderation/log.js';
export * as nuclear from './moderation/nuclear.js';
export * as premiado from './premiados/premiado.js';
export * as premiar from './premiados/premiar.js';
export * as mestres from './tops/mestres.js';
export * as top from './tops/top.js';
export * as calc from './util/calc.js';
export * as copy from './util/copy.js';
export * as hi from './util/hi.js';
export * as icon from './util/icon.js';
export * as debug from './util/debug.js'